import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {CSS2DRenderer,CSS2DObject} from 'three/addons/renderers/CSS2DRenderer.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {PARTS} from './motor-data.js';
import {buildMotor} from './motor-model.js';

const $=id=>document.getElementById(id),wrap=$('scene-wrap'),loading=$('loading'),infoTitle=$('part-title'),infoEn=$('part-en'),infoDesc=$('part-desc'),infoSpecs=$('part-specs'),partIcon=$('part-icon'),partsList=$('parts-list'),partsCount=$('parts-count'),rpmReadout=$('rpm-readout'),modeReadout=$('mode-readout'),speedSlider=$('speed-slider'),runBtn=$('run-btn'),explodeBtn=$('explode-btn'),labelsBtn=$('labels-btn'),resetBtn=$('reset-btn'),focusBtn=$('focus-btn');
const fa=n=>String(n).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);
partsCount.textContent=`${fa(Object.keys(PARTS).length)} جزء`;

const scene=new THREE.Scene();scene.background=new THREE.Color(0x03070a);scene.fog=new THREE.FogExp2(0x03070a,.026);
const camera=new THREE.PerspectiveCamera(40,innerWidth/innerHeight,.08,120);camera.position.set(12.2,7.1,13.6);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.65));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;wrap.appendChild(renderer.domElement);
const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.045).texture;pmrem.dispose();
const labelRenderer=new CSS2DRenderer();labelRenderer.setSize(innerWidth,innerHeight);Object.assign(labelRenderer.domElement.style,{position:'fixed',inset:'0',pointerEvents:'none',zIndex:'5'});wrap.appendChild(labelRenderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.06;controls.minDistance=7.2;controls.maxDistance=26;controls.target.set(0,.1,0);
scene.add(new THREE.HemisphereLight(0xcdeeff,0x08090b,1.7));const key=new THREE.DirectionalLight(0xe7f8ff,5.4);key.position.set(8,11,8);key.castShadow=true;key.shadow.mapSize.set(2048,2048);scene.add(key);const rim=new THREE.DirectionalLight(0x57dfff,2.2);rim.position.set(-8,4,-8);scene.add(rim);const warm=new THREE.PointLight(0xff8a52,22,18,2);warm.position.set(5,1,-6);scene.add(warm);const cyan=new THREE.PointLight(0x2edfff,30,20,2);cyan.position.set(-6,3,7);scene.add(cyan);

// Industrial presentation base
const floor=new THREE.Mesh(new THREE.CircleGeometry(11,128),new THREE.MeshPhysicalMaterial({color:0x071015,metalness:.65,roughness:.52}));floor.rotation.x=-Math.PI/2;floor.position.y=-3.55;floor.receiveShadow=true;scene.add(floor);const stage=new THREE.Mesh(new THREE.CylinderGeometry(5.4,5.75,.28,128),new THREE.MeshPhysicalMaterial({color:0x10181c,metalness:.86,roughness:.28}));stage.position.y=-3.43;stage.receiveShadow=true;scene.add(stage);const ring=new THREE.Mesh(new THREE.TorusGeometry(4.85,.025,8,128),new THREE.MeshBasicMaterial({color:0x4de6ff,transparent:true,opacity:.5}));ring.rotation.x=Math.PI/2;ring.position.y=-3.27;scene.add(ring);const grid=new THREE.GridHelper(34,34,0x1e5361,0x102b34);grid.position.y=-3.26;grid.material.transparent=true;grid.material.opacity=.17;scene.add(grid);

const motor=buildMotor(PARTS);scene.add(motor.root);
Object.entries(PARTS).forEach(([id,p])=>{const el=document.createElement('div');el.className='part-label';el.textContent=p.fa;const label=new CSS2DObject(el);label.position.set(...p.label);motor.groups[id].add(label)});

let selectionBox=null,selectedId=null,exploded=false,running=true,labelsVisible=true,speed=Number(speedSlider.value)/100,cameraTween=null;
const highlightedMeshes=[];
const glowColor=new THREE.Color(0x54eaff);
function clearPartGlow(){while(highlightedMeshes.length){const {mesh,original}=highlightedMeshes.pop();const current=mesh.material;mesh.material=original;mesh.userData.selectedGlow=false;if(Array.isArray(current))current.forEach(m=>m!==original&&m.dispose?.());else if(current!==original)current.dispose?.()}}
function makeGlowMaterial(material){const m=material.clone();if(m.color)m.color.lerp(new THREE.Color(0xc7fbff),.34);if(m.emissive){m.emissive.copy(glowColor);m.emissiveIntensity=Math.max(m.emissiveIntensity||0,1.35)}if('clearcoat'in m)m.clearcoat=Math.max(m.clearcoat||0,.42);m.needsUpdate=true;return m}
function applyPartGlow(group){clearPartGlow();group.traverse(o=>{if(!o.isMesh||!o.material)return;const original=o.material;o.material=Array.isArray(original)?original.map(makeGlowMaterial):makeGlowMaterial(original);o.userData.selectedGlow=true;highlightedMeshes.push({mesh:o,original})})}

Object.entries(PARTS).forEach(([id,p])=>{const b=document.createElement('button');b.className='part-item';b.dataset.id=id;b.innerHTML=`<span class="mini-icon">${p.icon}</span><div><strong>${p.fa}</strong><span>${p.en}</span></div>`;b.addEventListener('click',()=>selectPart(id,true));partsList.appendChild(b)});
function selectPart(id,focus=false){const p=PARTS[id],g=motor.groups[id];if(!p||!g)return;selectedId=id;applyPartGlow(g);infoTitle.textContent=p.fa;infoEn.textContent=p.en;infoDesc.textContent=p.desc;partIcon.textContent=p.icon;infoSpecs.innerHTML=p.specs.map(([a,b])=>`<div><span>${a}</span><strong>${b}</strong></div>`).join('');document.querySelectorAll('.part-item').forEach(x=>x.classList.toggle('active',x.dataset.id===id));if(selectionBox){scene.remove(selectionBox);selectionBox.geometry.dispose();selectionBox.material.dispose()}selectionBox=new THREE.BoxHelper(g,0x5ee8ff);selectionBox.material.transparent=true;selectionBox.material.opacity=.72;scene.add(selectionBox);if(focus)focusPart(id)}
const ease=t=>t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;
function focusPart(id){const g=motor.groups[id];if(!g)return;const b=new THREE.Box3().setFromObject(g),c=b.getCenter(new THREE.Vector3()),s=b.getSize(new THREE.Vector3()),max=Math.max(s.x,s.y,s.z),dir=camera.position.clone().sub(controls.target).normalize(),dest=c.clone().add(dir.multiplyScalar(Math.max(4.8,max*2.45)));cameraTween={start:performance.now(),duration:850,fromPos:camera.position.clone(),toPos:dest,fromTarget:controls.target.clone(),toTarget:c}}
function resetCamera(){cameraTween={start:performance.now(),duration:900,fromPos:camera.position.clone(),toPos:new THREE.Vector3(12.2,7.1,13.6),fromTarget:controls.target.clone(),toTarget:new THREE.Vector3(0,.1,0)}}
focusBtn.addEventListener('click',()=>selectedId&&focusPart(selectedId));resetBtn.addEventListener('click',resetCamera);runBtn.addEventListener('click',()=>{running=!running;runBtn.classList.toggle('active',running);runBtn.setAttribute('aria-pressed',String(running));runBtn.querySelector('.ico').textContent=running?'▶':'❚❚'});explodeBtn.addEventListener('click',()=>{exploded=!exploded;explodeBtn.classList.toggle('active',exploded);explodeBtn.setAttribute('aria-pressed',String(exploded));modeReadout.textContent=exploded?'نمای انفجاری مهندسی':'حالت آموزشی'});labelsBtn.addEventListener('click',()=>{labelsVisible=!labelsVisible;labelsBtn.classList.toggle('active',labelsVisible);labelsBtn.setAttribute('aria-pressed',String(labelsVisible));labelRenderer.domElement.classList.toggle('labels-hidden',!labelsVisible)});speedSlider.addEventListener('input',()=>speed=Number(speedSlider.value)/100);

const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let down={x:0,y:0};renderer.domElement.addEventListener('pointerdown',e=>down={x:e.clientX,y:e.clientY});renderer.domElement.addEventListener('pointerup',e=>{if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>7)return;const rect=renderer.domElement.getBoundingClientRect();pointer.x=((e.clientX-rect.left)/rect.width)*2-1;pointer.y=-((e.clientY-rect.top)/rect.height)*2+1;raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(motor.meshes,false).find(h=>!h.object.userData.skipRaycast);if(hit?.object?.userData?.componentId)selectPart(hit.object.userData.componentId,false)});
function updateExplode(){Object.values(motor.groups).forEach(g=>{const target=exploded?g.userData.basePosition.clone().add(g.userData.explodeOffset):g.userData.basePosition;g.position.lerp(target,.075)})}
const clock=new THREE.Clock();function animate(){const dt=Math.min(clock.getDelta(),.033),t=performance.now()/1000;controls.update();updateExplode();if(running){const omega=(.6+speed*5)*dt;motor.rotating.forEach(g=>g.rotation.x-=omega)}rpmReadout.textContent=`${fa(running?Math.round(450+speed*11550):0)} RPM`;motor.emissive.forEach((m,i)=>{'emissiveIntensity'in m.material&&(m.material.emissiveIntensity=m.userData.selectedGlow?1.35:.1+(running?.15+.14*Math.sin(t*6+i*.42):.02))});motor.field.forEach((o,i)=>{const a=o.angle+(running?t*(1.2+speed*2.7):0)+o.phase*2.094;o.dot.position.y=Math.cos(a)*1.72;o.dot.position.z=Math.sin(a)*1.72;o.dot.material.opacity=running?.28+.28*(.5+.5*Math.sin(t*4+i)):.05});cyan.intensity=26+(running?7*Math.sin(t*2.1):0);if(selectionBox)selectionBox.update();if(cameraTween){const q=Math.min(1,(performance.now()-cameraTween.start)/cameraTween.duration),e=ease(q);camera.position.lerpVectors(cameraTween.fromPos,cameraTween.toPos,e);controls.target.lerpVectors(cameraTween.fromTarget,cameraTween.toTarget,e);if(q>=1)cameraTween=null}renderer.render(scene,camera);labelRenderer.render(scene,camera)}renderer.setAnimationLoop(animate);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);labelRenderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.65))});selectPart('stator',false);setTimeout(()=>loading.classList.add('hidden'),950);
